In [9]:
import numpy

$$
x + 3y = 5 \\
2x + 4y = 8
$$

In [10]:
A = numpy.array([
    [1, 3],
    [2, 4]
])

b = numpy.array([
    5,
    8
])

A, b

(array([[1, 3],
        [2, 4]]),
 array([5, 8]))

$$
u = (x, y) = A^{-1} b
$$

In [11]:
# A u = b
# u = A' b
u = numpy.linalg.inv(A).dot(b)
u

array([2., 1.])

Problema inverso

In [17]:
u, b

(array([2., 1.]), array([5, 8]))

In [20]:
M = numpy.array([
    [1, 3],
    [2, 4]
])

In [ ]:
M.dot(u) # b = M u

array([5., 8.])

In [ ]:
numpy.linalg.inv(M).dot(b) # u = M' b

array([2., 1.])

In [ ]:
M = numpy.random.rand(2, 2)

b1 = numpy.random.uniform(-1, 2)
b2 = numpy.random.uniform(2, 4)
b3 = numpy.random.uniform(1, 3)
b4 = numpy.random.uniform(3, 5)

M[0, 0] = b1
M[0, 1] = b2
M[1, 0] = b3
M[1, 1] = b4

M

array([[1.71675542, 2.64634502],
       [1.20193578, 3.27225275]])

In [48]:
((M.dot(u) - b) ** 2).sum()

6.566486914222762

In [49]:
def loss(M, u, b):
    return ((M.dot(u) - b) ** 2).sum()

In [50]:
loss(M, u, b)

6.566486914222762

In [59]:
def optimizer_naive_step(b1, b2, b3, b4, loss, u, b):
    b1p = numpy.random.normal(b1, 1)
    b2p = numpy.random.normal(b2, 1)
    b3p = numpy.random.normal(b3, 1)
    b4p = numpy.random.normal(b4, 1)

    M = numpy.array([
        [b1, b2],
        [b3, b4],
    ])
    Mp = numpy.array([
        [b1p, b2p],
        [b3p, b4p],
    ])

    if loss(M, u, b) < loss(Mp, u, b):
        return b1, b2, b3, b4, loss(M, u, b)
    else:
        return b1p, b2p, b3p, b4p, loss(Mp, u, b)

In [56]:
b1, b2, b3, b4 = numpy.random.rand(4)
b1, b2, b3, b4

(0.5764922327894164,
 0.5490468548669175,
 0.16427380599215413,
 0.7457406704426193)

In [78]:
b1, b2, b3, b4, l = optimizer_naive_step(b1, b2, b3, b4, loss, u, b)
b1, b2, b3, b4, l

(3.5842452712697748,
 -0.3602914305217815,
 3.4333551327677196,
 1.5935722820175227,
 3.4814440522836883)

In [79]:
for epoch in range(100_000):
    b1, b2, b3, b4, l = optimizer_naive_step(b1, b2, b3, b4, loss, u, b)

b1, b2, b3, b4, l

(1.8569821329582514,
 1.278535620841792,
 2.762439664011236,
 2.461854254036112,
 0.00023224954363473547)

In [80]:
M_opt = numpy.array([
    [1.8569821329582514, 1.278535620841792],
    [ 2.762439664011236, 2.461854254036112]
])

M_opt

array([[1.85698213, 1.27853562],
       [2.76243966, 2.46185425]])

In [81]:
M_opt.dot(u)

array([4.99249989, 7.98673358])

In [82]:
numpy.linalg.inv(M_opt).dot(b)

array([2.00144516, 1.00376718])